const pizzas = [
  { id: 1, name: "Margherita Supreme", emoji: "🍕", image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=480&h=320&fit=crop&auto=format&q=80", description: "San Marzano tomatoes, fresh mozzarella, hand-torn basil, extra virgin olive oil", price: 349, originalPrice: 449, calories: 820, rating: 4.8, reviews: 3241, category: "Classic", tags: ["vegetarian","mild","thin-crust"], ingredients: ["Tomato Sauce","Mozzarella","Fresh Basil","Olive Oil"], crust: "thin", spice: "mild", isVeg: true, gradient: "from-red-500 to-orange-500" },
  { id: 2, name: "Pepperoni Paradise", emoji: "🍕", image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=480&h=320&fit=crop&auto=format&q=80", description: "Double-layered pepperoni, smoked mozzarella, zesty marinara, oregano crust", price: 449, originalPrice: 549, calories: 1080, rating: 4.9, reviews: 5892, category: "Meat Lover", tags: ["spicy","thick-crust"], ingredients: ["Pepperoni","Smoked Mozzarella","Marinara","Oregano"], crust: "thick", spice: "medium", isVeg: false, gradient: "from-rose-600 to-red-700" },
  { id: 3, name: "BBQ Chicken Feast", emoji: "🍕", image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=480&h=320&fit=crop&auto=format&q=80", description: "Grilled chicken, smoky BBQ sauce, caramelized onions, cheddar blend", price: 499, originalPrice: 599, calories: 1020, rating: 4.7, reviews: 2104, category: "Chicken", tags: ["mild","thick-crust"], ingredients: ["Grilled Chicken","BBQ Sauce","Caramelized Onions","Cheddar"], crust: "thick", spice: "mild", isVeg: false, gradient: "from-amber-500 to-orange-600" },
  { id: 4, name: "Paneer Tikka Special", emoji: "🍕", image: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=480&h=320&fit=crop&auto=format&q=80", description: "Tandoori paneer, capsicum, onions, tikka masala base, mozzarella", price: 429, originalPrice: 529, calories: 900, rating: 4.8, reviews: 4310, category: "Indian", tags: ["vegetarian","spicy","thin-crust"], ingredients: ["Paneer","Capsicum","Tikka Masala","Mozzarella"], crust: "thin", spice: "spicy", isVeg: true, gradient: "from-orange-500 to-amber-600" },
  { id: 5, name: "Mushroom Truffle", emoji: "🍕", image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=480&h=320&fit=crop&auto=format&q=80", description: "Wild porcini, shiitake, truffle oil, aged parmesan, garlic cream base", price: 549, originalPrice: 699, calories: 860, rating: 4.6, reviews: 1876, category: "Gourmet", tags: ["vegetarian","mild","thin-crust"], ingredients: ["Porcini","Shiitake","Truffle Oil","Parmesan"], crust: "thin", spice: "mild", isVeg: true, gradient: "from-stone-500 to-neutral-600" },
  { id: 6, name: "Spicy Inferno", emoji: "🍕", image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=480&h=320&fit=crop&auto=format&q=80", description: "Ghost pepper sauce, habanero chicken, jalapeños, pepper jack, fiery crust", price: 479, originalPrice: 579, calories: 1100, rating: 4.5, reviews: 2987, category: "Spicy", tags: ["very-spicy","thin-crust"], ingredients: ["Ghost Pepper Sauce","Habanero Chicken","Jalapeños","Pepper Jack"], crust: "thin", spice: "extra-spicy", isVeg: false, gradient: "from-red-600 to-rose-800" },
  { id: 7, name: "Four Cheese Blend", emoji: "🍕", image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=480&h=320&fit=crop&auto=format&q=80", description: "Mozzarella, cheddar, gouda, parmesan, white cream base, herbs", price: 399, originalPrice: 499, calories: 1060, rating: 4.7, reviews: 3654, category: "Classic", tags: ["vegetarian","mild"], ingredients: ["Mozzarella","Cheddar","Gouda","Parmesan"], crust: "stuffed", spice: "mild", isVeg: true, gradient: "from-yellow-400 to-amber-500" },
  { id: 8, name: "Garden Fresh", emoji: "🍕", image: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=480&h=320&fit=crop&auto=format&q=80", description: "Cherry tomatoes, spinach, zucchini, bell peppers, basil pesto, ricotta", price: 379, originalPrice: 459, calories: 720, rating: 4.4, reviews: 1423, category: "Vegetarian", tags: ["vegetarian","mild","healthy"], ingredients: ["Cherry Tomatoes","Spinach","Zucchini","Bell Peppers"], crust: "thin", spice: "mild", isVeg: true, gradient: "from-green-500 to-emerald-600" },
  { id: 9, name: "Chicken Tandoori", emoji: "🍕", image: "https://images.unsplash.com/photo-1588315029754-2dd089d39a1a?w=480&h=320&fit=crop&auto=format&q=80", description: "Tandoori marinated chicken, red onions, mint chutney drizzle, mozzarella", price: 469, originalPrice: 569, calories: 960, rating: 4.9, reviews: 6102, category: "Indian", tags: ["spicy","thick-crust"], ingredients: ["Tandoori Chicken","Red Onion","Mint Chutney","Mozzarella"], crust: "thick", spice: "spicy", isVeg: false, gradient: "from-orange-600 to-red-600" },
  { id: 10, name: "Classic Hawaiian", emoji: "🍕", image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=480&h=320&fit=crop&auto=format&q=80", description: "Ham, fresh pineapple, mozzarella, tomato sauce, a touch of chili flakes", price: 399, originalPrice: 479, calories: 880, rating: 4.3, reviews: 2198, category: "Classic", tags: ["mild","thick-crust"], ingredients: ["Ham","Pineapple","Mozzarella","Tomato Sauce"], crust: "thick", spice: "mild", isVeg: false, gradient: "from-yellow-500 to-orange-500" },
  { id: 11, name: "Meat Supreme", emoji: "🍕", image: "https://images.unsplash.com/photo-1548369937-47519962c11a?w=480&h=320&fit=crop&auto=format&q=80", description: "Pepperoni, sausage, bacon, ham, ground beef, smoky BBQ drizzle", price: 569, originalPrice: 699, calories: 1280, rating: 4.8, reviews: 4521, category: "Meat Lover", tags: ["spicy","stuffed-crust"], ingredients: ["Pepperoni","Sausage","Bacon","Ham","Ground Beef"], crust: "stuffed", spice: "medium", isVeg: false, gradient: "from-red-700 to-rose-900" },
  { id: 12, name: "Pesto Basil", emoji: "🍕", image: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=480&h=320&fit=crop&auto=format&q=80", description: "Homemade basil pesto, sun-dried tomatoes, pine nuts, burrata, arugula", price: 519, originalPrice: 619, calories: 810, rating: 4.6, reviews: 1654, category: "Gourmet", tags: ["vegetarian","mild","thin-crust"], ingredients: ["Basil Pesto","Sun-dried Tomatoes","Pine Nuts","Burrata"], crust: "thin", spice: "mild", isVeg: true, gradient: "from-green-600 to-teal-600" },
  { id: 13, name: "Buffalo Chicken", emoji: "🍕", image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=480&h=320&fit=crop&auto=format&q=80", description: "Buffalo tossed chicken, blue cheese drizzle, celery, mozzarella, ranch base", price: 489, originalPrice: 589, calories: 1040, rating: 4.7, reviews: 3210, category: "Chicken", tags: ["spicy","thick-crust"], ingredients: ["Buffalo Chicken","Blue Cheese","Celery","Ranch"], crust: "thick", spice: "spicy", isVeg: false, gradient: "from-orange-600 to-amber-700" },
  { id: 14, name: "Smoky Bacon", emoji: "🍕", image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=480&h=320&fit=crop&auto=format&q=80", description: "Double smoked bacon, caramelized onions, gruyere, honey mustard base", price: 459, originalPrice: 559, calories: 1120, rating: 4.6, reviews: 2341, category: "Meat Lover", tags: ["mild","thick-crust"], ingredients: ["Double Smoked Bacon","Caramelized Onions","Gruyere","Honey Mustard"], crust: "thick", spice: "mild", isVeg: false, gradient: "from-amber-700 to-orange-800" },
  { id: 15, name: "Mediterranean Veg", emoji: "🍕", image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=480&h=320&fit=crop&auto=format&q=80", description: "Kalamata olives, artichokes, feta, roasted red peppers, oregano, olive oil", price: 419, originalPrice: 519, calories: 780, rating: 4.5, reviews: 1876, category: "Vegetarian", tags: ["vegetarian","mild","thin-crust"], ingredients: ["Kalamata Olives","Artichokes","Feta","Roasted Peppers"], crust: "thin", spice: "mild", isVeg: true, gradient: "from-blue-500 to-indigo-600" },
  { id: 16, name: "Double Pepperoni", emoji: "🍕", image: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=480&h=320&fit=crop&auto=format&q=80", description: "Two full layers of premium pepperoni cups, mozzarella, tomato, hot honey finish", price: 499, originalPrice: 599, calories: 1200, rating: 5.0, reviews: 7823, category: "Meat Lover", tags: ["spicy","thick-crust"], ingredients: ["Double Pepperoni","Mozzarella","Tomato Sauce","Hot Honey"], crust: "thick", spice: "medium", isVeg: false, gradient: "from-rose-500 to-red-700" },
  { id: 17, name: "Paneer & Corn", emoji: "🍕", image: "https://images.unsplash.com/photo-1588315029754-2dd089d39a1a?w=480&h=320&fit=crop&auto=format&q=80", description: "Sweet corn, paneer cubes, capsicum, tomato base, mozzarella, oregano", price: 389, originalPrice: 469, calories: 860, rating: 4.4, reviews: 2103, category: "Indian", tags: ["vegetarian","mild"], ingredients: ["Sweet Corn","Paneer","Capsicum","Mozzarella"], crust: "thick", spice: "mild", isVeg: true, gradient: "from-yellow-400 to-green-500" },
  { id: 18, name: "Jalapeño Fiesta", emoji: "🍕", image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=480&h=320&fit=crop&auto=format&q=80", description: "Fresh jalapeños, pickled jalapeños, chorizo, manchego, chipotle base", price: 469, originalPrice: 569, calories: 1050, rating: 4.6, reviews: 2765, category: "Spicy", tags: ["very-spicy","thin-crust"], ingredients: ["Fresh Jalapeños","Chorizo","Manchego","Chipotle Sauce"], crust: "thin", spice: "extra-spicy", isVeg: false, gradient: "from-green-600 to-red-600" },
  { id: 19, name: "Truffle Mushroom Luxe", emoji: "🍕", image: "https://images.unsplash.com/photo-1548369937-47519962c11a?w=480&h=320&fit=crop&auto=format&q=80", description: "Black truffle paste, cremini mushrooms, fontina, shallots, fresh thyme", price: 649, originalPrice: 799, calories: 890, rating: 4.9, reviews: 1432, category: "Gourmet", tags: ["vegetarian","mild","premium"], ingredients: ["Black Truffle","Cremini Mushrooms","Fontina","Shallots"], crust: "thin", spice: "mild", isVeg: true, gradient: "from-neutral-600 to-stone-700" },
  { id: 20, name: "The Classic Italian", emoji: "🍕", image: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=480&h=320&fit=crop&auto=format&q=80", description: "Prosciutto, salami, roasted garlic, cherry tomatoes, fresh mozzarella, basil oil", price: 579, originalPrice: 679, calories: 970, rating: 4.8, reviews: 3987, category: "Gourmet", tags: ["mild","thin-crust","premium"], ingredients: ["Prosciutto","Salami","Roasted Garlic","Cherry Tomatoes"], crust: "thin", spice: "mild", isVeg: false, gradient: "from-red-500 to-green-600" },
]

const deals = [
  { id: 1, title: "Double Trouble", description: "Buy any 2 large pizzas and get a free garlic bread + 2 drinks", originalPrice: 1098, discountedPrice: 699, savings: 399, code: "DOUBLE399", tag: "Best Value", tagColor: "from-orange-500 to-red-500", emoji: "🍕", expiresInHours: 5, badge: "HOT" },
  { id: 2, title: "Lunch Express", description: "1 medium pizza + garlic bread + cold drink — weekday lunch special", originalPrice: 699, discountedPrice: 399, savings: 300, code: "LUNCH300", tag: "Lunch Deal", tagColor: "from-yellow-500 to-orange-500", emoji: "⏰", expiresInHours: 2, badge: "LIMITED" },
  { id: 3, title: "Party Pack", description: "4 large pizzas + 4 sides + 4 drinks — feed the whole crew", originalPrice: 2800, discountedPrice: 1799, savings: 1001, code: "PARTY1001", tag: "Party Pack", tagColor: "from-purple-500 to-pink-500", emoji: "🎉", expiresInHours: 12, badge: "NEW" },
  { id: 4, title: "Veggie Fiesta", description: "Any 3 vegetarian pizzas at a flat 35% off — guilt-free indulgence", originalPrice: 1197, discountedPrice: 779, savings: 418, code: "VEG418", tag: "Veg Special", tagColor: "from-green-500 to-teal-500", emoji: "🥗", expiresInHours: 8, badge: "TRENDING" },
  { id: 5, title: "First Order", description: "New to Pizzora? Get 40% off your first order — no minimum order", originalPrice: 500, discountedPrice: 300, savings: 200, code: "FIRST200", tag: "New User", tagColor: "from-blue-500 to-indigo-500", emoji: "👋", expiresInHours: 72, badge: "NEW" },
  { id: 6, title: "Midnight Munchies", description: "Order between 11PM–2AM and get flat ₹150 off + free cheesy dip", originalPrice: 600, discountedPrice: 450, savings: 150, code: "NIGHT150", tag: "Late Night", tagColor: "from-indigo-500 to-purple-600", emoji: "🌙", expiresInHours: 3, badge: "FLASH" },
]

const reviews = [
  { id: 1, name: "Arjun Mehta", avatar: "A", avatarColor: "from-orange-500 to-amber-500", rating: 5, review: "The AI recommendations are shockingly accurate — it suggested the Paneer Tikka and now it's my go-to. The app is gorgeous too, feels premium.", pizza: "Paneer Tikka Special", date: "2 days ago", verified: true, likes: 124 },
  { id: 2, name: "Priya Sharma", avatar: "P", avatarColor: "from-pink-500 to-rose-500", rating: 5, review: "Used the pizza quiz before ordering and it nailed exactly what I wanted. The Truffle Mushroom Luxe was restaurant-quality. Ordering again tonight!", pizza: "Truffle Mushroom Luxe", date: "1 week ago", verified: true, likes: 89 },
  { id: 3, name: "Rahul Gupta", avatar: "R", avatarColor: "from-blue-500 to-indigo-500", rating: 5, review: "Group voting feature is a game changer for office orders. No more 20-minute arguments about what to get. Everyone's happy, especially me.", pizza: "Double Pepperoni", date: "3 days ago", verified: true, likes: 203 },
  { id: 4, name: "Sneha Reddy", avatar: "S", avatarColor: "from-green-500 to-teal-500", rating: 4, review: "The pizza builder is so fun! Spent way too long customizing but it was worth it. The live calorie counter is a nice reality check.", pizza: "Custom Build", date: "5 days ago", verified: true, likes: 67 },
  { id: 5, name: "Karan Malhotra", avatar: "K", avatarColor: "from-purple-500 to-violet-500", rating: 5, review: "Fastest delivery, hottest pizza. The Double Pepperoni is absolutely unreal — that hot honey finish changes everything.", pizza: "Double Pepperoni", date: "1 day ago", verified: true, likes: 156 },
  { id: 6, name: "Anita Patel", avatar: "A", avatarColor: "from-yellow-500 to-orange-500", rating: 5, review: "I'm vegetarian and was skeptical but the quiz perfectly matched me to Garden Fresh and Mediterranean Veg. Both incredible.", pizza: "Garden Fresh", date: "4 days ago", verified: true, likes: 94 },
]

const COUPONS = { DOUBLE399: 399, LUNCH300: 300, PARTY1001: 1001, VEG418: 418, FIRST200: 200, NIGHT150: 150, PIZZORA10: 100, SAVE50: 50 }

// In-memory orders store
const orders = []

module.exports = { pizzas, deals, reviews, COUPONS, orders }
